sequenceDiagram
  autonumber
  participant OS as OnlineStore
  participant PAY as Payments
  participant ORD as Orders
  participant GC as GiftCertificateProcessing
  participant SMS as SMS Gateway
  participant BI as BI Pipeline

  OS->>ORD: Создание заказа (Gift Certificate)
  ORD-->>GC: Event All_SalesOrder
  OS->>GC: POST /certificates/{code}/authorize
  alt Код уже продан
    GC-->>OS: 409 CodeAlreadySold
  else Код свободен
    GC->>GC: Резервировать код за каналом
    GC-->>OS: AuthorizationId, резерв подтверждён
    loop Частичные оплаты
      OS->>PAY: Подтвердить оплату
      PAY-->>GC: Event All_Payments (version N, outstandingAmount > 0)
      GC->>GC: Обновить агрегированные суммы
    end
    PAY-->>GC: Event All_Payments (isOrderSettled=true, outstandingAmount = 0)
    GC->>GC: Изменить статус сертификата на Active
    GC-->>SMS: Отправить CVC по SMS
    GC-->>BI: Publish GiftCertificateTransaction(Activate)
    GC-->>Kafka: Publish GiftCertificateState
  end

  alt Частичная оплата заказом
    OS->>GC: POST /certificates/{code}/authorize
    GC-->>OS: AuthorizationId, доступный баланс
    OS->>PAY: Подтвердить оплату
    PAY->>GC: POST /certificates/{code}/capture
    GC->>GC: Списать сумму, обновить баланс
    GC-->>BI: Publish GiftCertificateTransaction(Capture)
    GC-->>Kafka: Publish GiftCertificateState
  else Отмена
    PAY->>GC: POST /certificates/{code}/void
    GC->>GC: Восстановить баланс
    GC-->>BI: Publish GiftCertificateTransaction(Void)
    GC-->>Kafka: Publish GiftCertificateState
  end
